sot_controller:
  type: tiago_roscontrol_test/TiagoRosControlTest
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
    - gripper_finger_joint
    - head_1_joint
    - head_2_joint
    - torso_lift_joint
