tiago_roscontrol_test:
  simulation_mode: gazebo
  joint_names: [
    wheel_left_joint, wheel_right_joint,
    torso_lift_joint,
    arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint, gripper_left_finger_joint, gripper_right_finger_joint,
    head_1_joint, head_2_joint  ]
  control_mode:
    wheel_left_joint:
      ros_control_mode: VELOCITY
    wheel_right_joint:
      ros_control_mode: VELOCITY
    torso_lift_joint:
      ros_control_mode: POSITION
    arm_1_joint:
      ros_control_mode: POSITION
    arm_2_joint:
      ros_control_mode: POSITION
    arm_3_joint:
      ros_control_mode: POSITION
    arm_4_joint:
      ros_control_mode: POSITION
    arm_5_joint:
      ros_control_mode: POSITION
    arm_6_joint:
      ros_control_mode: POSITION
    arm_7_joint:
      ros_control_mode: POSITION
    gripper_left_finger_joint:
      ros_control_mode: POSITION
    gripper_right_finger_joint:
      ros_control_mode: POSITION
    head_1_joint:
      ros_control_mode: POSITION
    head_2_joint:
      ros_control_mode: POSITION
